from_email = "radical_ed@beebop.org"
imap_login = "bogusdata"
imap_server = "beebop"
imap_session = "inbox"
imap_starting_at = "0"
irc_server = "utopiaplanitia.net:6667"
irc_user = "radical_ed"
irc_nick = "radical_ed"
irc_first_name = "radical"
irc_last_name = "ed"
