from_email = "radical_ed@beebop.org"
imap_login = "yancy@yancy.lol"
imap_server = "mail.gandi.net"
imap_session = "inbox"
imap_starting_at = "2065"
irc_server = "chat.freenode.net:6667"
irc_user = "radical_ed"
irc_nick = "radical_ed"
irc_first_name = "radical"
irc_last_name = "ed"
